# Jekyll configuration for Open SDG platform

# Tell the Remote Theme plugin to use the Open SDG platform (Jekyll theme).
remote_theme: open-sdg/open-sdg@2.2.0

# Replace this title as needed.
title: general.site_title
url: ""
environment: staging

date_formats:
  - type: standard
    language: de
    format: "%d.%m.%Y"
  - type: standard
    language: en
    format: "%b %d, %Y"

# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true

metadata_tabs:
  - scope: national
    title: indicator.details
    description: indicator.dns_metadata_blurb
  - scope: content
    title: indicator.contentAndProgress
    description: ''
  - scope: history_1
    title: indicator.history
    description: indicator.history_blurb
  - scope: sources
    title: indicator.sources
    description: ''
# Configure the text (or "translation key") to be used on the
# non-global metadata tab.
non_global_metadata: indicator.national_metadata

search_index_extra_fields:
  #- indicator_number
  - national_indicator_available
  - indicator_name
  - target_name
  - target_id
  - data_keywords
  - graph_title

footer_fields:
  - unit: '%'
    label: metadata_fields.computation_units
    value: data.%
  - unit: number
    label: metadata_fields.computation_units
    value: data.number


series_toggle: true
graph_title_from_series: false
decimal_separator: ','
thousands_separator: ' '
#graph_color_headline: '#b8b8b8' #
graph_color_headline: ['#e5243b', '#dda63a', '#4c9f38', '#c5192d', '#ff3a21', '#26bde2', '#fcc30b', '#a21942', '#fd6925', '#dd1367', '#fd9d24', '#bf8b2e', '#3f7e44', '#0a97d9', '#56c02b', '#00689d', '#19486a']
useHeadlineColor: false
no_value_character: ' '

# Tell Jekyll to use the Remote Theme plugin.
plugins:
  - jekyll-remote-theme
  - jekyll-open-sdg-plugins

# Exclude some files/folders.
exclude:
  - vendor
  - scripts
  - remotedata
  - Gemfile
  - Gemfile.lock
  - README
  - README.md
  - LICENSE

